#!/usr/bin/env python3
"""
Cross-validation MIL training entry point used by the dashboard.

This script is intentionally lightweight—it delegates the heavy lifting to
``goldmark.training`` so the launchpad shares the exact trainer,
checkpoint layout, and metrics that power the CLI.  Each invocation receives
the normalized manifest generated by the dashboard, builds (or refreshes)
five split columns when they are missing, and writes per-split artifacts under
``<run_root>/checkpoints/<TARGET>/<encoder>/<AGGREGATOR>/split_*`` so
the rest of the site (download center, visualizations, etc.) can reuse them.
"""

from __future__ import annotations

import argparse
import sys
import json
import logging
from dataclasses import replace
from datetime import datetime
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

import pandas as pd
from sklearn.model_selection import StratifiedKFold

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.append(str(REPO_ROOT))

from goldmark.training import TrainerConfig, run_cross_validation  # noqa: E402
from goldmark.utils.logging import get_logger  # noqa: E402


LOGGER = get_logger("train_task_v2")


def _load_shell_config(path: Path) -> dict:
    config: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:]
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        config[key.strip()] = value.strip().strip('"').strip("'")
    return config


def _existing_split_columns(df: pd.DataFrame) -> List[str]:
    columns = [col for col in df.columns if col.lower().startswith("split_")]
    return [col for col in columns if df[col].notna().any()]


def _ensure_split_columns(
    df: pd.DataFrame,
    target_column: str,
    folds: int,
    seed: int = 42,
) -> Tuple[pd.DataFrame, List[str]]:
    working = df.copy()
    existing = _existing_split_columns(working)
    if existing:
        for column in existing:
            working[column] = (
                working[column].astype(str).str.strip().str.lower().replace({"validation": "val"})
            )
        return working, existing

    valid = working[working[target_column].notna()].copy()
    if valid.empty:
        raise ValueError(f"No valid rows for target column '{target_column}'.")
    labels = valid[target_column].astype(int)
    folds = max(2, min(folds, len(valid)))
    skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=seed)

    generated: List[str] = []
    for idx, (_, test_idx) in enumerate(skf.split(valid, labels), start=1):
        column = f"split_{idx}_set"
        working[column] = "train"
        working.loc[valid.iloc[test_idx].index, column] = "test"
        generated.append(column)
    return working, generated


def _target_stats(series: pd.Series) -> dict:
    valid = series.dropna()
    total = int(series.size)
    valid_count = int(valid.size)
    positives = int((valid > 0.5).sum())
    negatives = int((valid <= 0.5).sum())
    prevalence = float(positives / valid_count) if valid_count else float("nan")
    return {
        "total_rows": total,
        "valid_rows": valid_count,
        "positives": positives,
        "negatives": negatives,
        "prevalence": prevalence,
    }


def _write_split_manifest(
    manifest: pd.DataFrame,
    target_column: str,
    split_columns: Iterable[str],
    aggregator_dir: Path,
) -> None:
    encoder_dir = aggregator_dir.parent
    manifest_dir = encoder_dir / "manifests"
    manifest_dir.mkdir(parents=True, exist_ok=True)

    preferred_ids = ["case_id", "slide_id", "DMP_ASSAY_ID", "sample_id", "slide_name"]
    id_column = next((col for col in preferred_ids if col in manifest.columns), None)
    target_series = manifest[target_column]
    target_numeric = pd.to_numeric(target_series, errors="coerce")
    payload = pd.DataFrame()
    if id_column:
        payload[id_column] = manifest[id_column]
    payload["target"] = target_numeric.fillna(0).astype(int)
    for column in split_columns:
        payload[column] = manifest[column].astype(str)

    filename = f"{target_column.upper()}_all_splits.csv"
    payload.to_csv(manifest_dir / filename, index=False)


def _trainer_config_from_shell(
    config: dict,
    encoder_name: Optional[str],
    epochs_override: Optional[int],
    val_interval_override: Optional[int],
) -> TrainerConfig:
    epochs = epochs_override or int(config.get("NUM_EPOCHS", 50))
    interval_candidate = val_interval_override or int(config.get("VAL_INTERVAL", 1))
    val_interval = max(1, interval_candidate)
    extra = config.get("EXTRA_VAL_EPOCHS", "")
    extra_list = [int(x.strip()) for x in extra.split(",") if x.strip().isdigit()]
    return TrainerConfig(
        aggregator=(config.get("AGGREGATION_METHOD") or "gma"),
        epochs=epochs,
        batch_size=int(config.get("BATCH_SIZE_TRAIN", 32)),
        learning_rate=float(config.get("LEARNING_RATE", 1e-4)),
        weight_decay=float(config.get("WEIGHT_DECAY", 1e-4)),
        patience=int(config.get("PATIENCE", 8)),
        split_column=config.get("SPLIT_COLUMN", "split"),
        train_split_value=config.get("TRAIN_VALUE", "train"),
        val_split_value=config.get("VAL_VALUE", "test"),
        test_split_value=config.get("TEST_VALUE", "test"),
        dropout=True,
        device=config.get("DEVICE", "cuda"),
        num_workers=int(config.get("NUM_WORKERS", 4)),
        encoder_name=encoder_name,
        val_interval=val_interval,
        extra_val_epochs=extra_list,
    )


def _coerce_target(series: pd.Series, column: str) -> pd.Series:
    numeric = pd.to_numeric(series, errors="coerce")
    if numeric.notna().any():
        return numeric
    normalized = series.astype(str).str.strip().str.lower()
    positive_tokens = {"positive", "pos", "mutant", "mutated", "yes", "true", "1", "high"}
    negative_tokens = {"negative", "neg", "wildtype", "wt", "no", "false", "0", "low"}
    mapped = normalized.map(
        lambda value: 1
        if value in positive_tokens
        else 0
        if value in negative_tokens
        else None
    )
    if mapped.notna().any():
        return mapped.astype(float)
    raise ValueError(
        f"Target column '{column}' cannot be coerced to numeric values. "
        f"Example entries: {list(normalized.dropna().unique()[:5])}"
    )


def _log_split_distribution(manifest: pd.DataFrame, split_columns: Iterable[str]) -> dict:
    distribution: dict[str, dict[str, int]] = {}
    for column in split_columns:
        counts = manifest[column].astype(str).str.lower().value_counts()
        summary = {label: int(value) for label, value in counts.items()}
        distribution[column] = summary
        LOGGER.info(
            "Split %s distribution: %s",
            column,
            ", ".join(f"{label}={count}" for label, count in summary.items()),
        )
    return distribution


def main() -> int:
    parser = argparse.ArgumentParser(description="Train MIL tasks using precomputed features.")
    parser.add_argument("--config", required=True, help="Shell-style config with export statements.")
    parser.add_argument("--manifest", required=True, help="Path to normalized manifest CSV.")
    parser.add_argument("--feature-dir", required=True, help="Directory containing feature tensors.")
    parser.add_argument("--target-column", required=True, help="Target column name.")
    parser.add_argument("--output-dir", required=True, help="Per-target/encoder checkpoint directory.")
    parser.add_argument("--log-level", default="INFO", help="Logging level (default: INFO).")
    parser.add_argument("--epochs", type=int, help="Override NUM_EPOCHS from the config.")
    parser.add_argument(
        "--val-interval",
        type=int,
        help="Validate every N epochs (default: VAL_INTERVAL from config, minimum 1).",
    )
    parser.add_argument("--encoder-name", help="Encoder slug (for metadata).")
    parser.add_argument("--encoder", help="Legacy alias for --encoder-name.", dest="encoder_alias")
    parser.add_argument("--aggregator", default="gma", help="Aggregator label for path annotations.")
    parser.add_argument("--total-epochs", type=int, help="Unused placeholder (progress handled by dashboard).")
    args = parser.parse_args()

    LOGGER.setLevel(args.log_level.upper())

    config_path = Path(args.config).expanduser()
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")
    shell_config = _load_shell_config(config_path)

    manifest_path = Path(args.manifest).expanduser()
    feature_dir = Path(args.feature_dir).expanduser()
    output_dir = Path(args.output_dir).expanduser()
    for path, label in ((manifest_path, "manifest"), (feature_dir, "feature directory")):
        if not path.exists():
            raise FileNotFoundError(f"{label.title()} not found: {path}")
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = pd.read_csv(manifest_path)
    target_column = args.target_column
    if target_column not in manifest.columns:
        raise ValueError(f"Target column '{target_column}' missing from manifest.")
    manifest[target_column] = _coerce_target(manifest[target_column], target_column)

    folds = int(shell_config.get("CV_FOLDS", 5))
    manifest, split_columns = _ensure_split_columns(manifest, target_column, folds)
    manifest.to_csv(manifest_path, index=False)
    target_summary = _target_stats(manifest[target_column])
    LOGGER.info(
        "Target %s stats — total=%d, valid=%d, positives=%d, negatives=%d, prevalence=%.3f",
        target_column,
        target_summary["total_rows"],
        target_summary["valid_rows"],
        target_summary["positives"],
        target_summary["negatives"],
        target_summary["prevalence"],
    )
    split_distribution = _log_split_distribution(manifest, split_columns)

    trainer_config = _trainer_config_from_shell(
        shell_config,
        args.encoder_name,
        args.epochs,
        args.val_interval,
    )
    trainer_config = replace(
        trainer_config,
        split_column=split_columns[0],
        train_split_value="train",
        val_split_value="test",
        test_split_value="test",
    )

    LOGGER.info("Training %s targets with %d folds (%s).", target_column, len(split_columns), ", ".join(split_columns))
    summary_df = run_cross_validation(
        manifest=manifest,
        feature_dir=feature_dir,
        base_output_dir=output_dir,
        target_column=target_column,
        base_config=trainer_config,
        split_columns=split_columns,
        log_level=args.log_level,
    )

    _write_split_manifest(manifest, target_column, split_columns, output_dir)
    report_dir = output_dir / "classification_report"
    encoder_label = args.encoder_name or args.encoder_alias
    audit_payload = {
        "target": target_column,
        "encoder": encoder_label,
        "aggregator": args.aggregator,
        "generated_at": datetime.utcnow().isoformat(),
        "target_stats": target_summary,
        "split_distribution": split_distribution,
        "metrics": summary_df.to_dict(orient="records"),
    }
    report_dir.mkdir(parents=True, exist_ok=True)
    audit_path = report_dir / "training_audit.json"
    audit_path.write_text(json.dumps(audit_payload, indent=2))
    LOGGER.info("Saved training audit report to %s", audit_path)
    LOGGER.info("Training complete. Artifacts saved to %s", output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
